apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-despliegue
spec:
  selector:
    matchLabels:
      app: mi-servidor
  replicas: 1
  template:
    metadata:
      labels:
        app: mi-servidor
    spec:
      containers:
      - name: mi-contenedor
        image: docker.io/zurisaddairj/fastapiml:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mi-servicio
  name: mi-servicio
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mi-servidor
  type: LoadBalancer